# .github/workflows/deploy.yml
name: Deploy FastAPI App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create .env file on runner
        run: |
          echo "${{ secrets.ENV_FILE }}" > ./src/.env

      - name: Copy project files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          source: "." # Copy all files from the current directory
          target: "~/myaca-ai" # The target directory on your EC2 instance

      - name: Execute deployment commands on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          script: |
            cd ~/myaca-ai
            
            # Install/update dependencies from requirements.txt
            pip install -r requirements.txt

            # Stop any currently running uvicorn process
            pkill -f "uvicorn src.main:app" || true

            # Start the FastAPI application in the background using nohup
            nohup uvicorn src.main:app --host 0.0.0.0 --port 8000 > uvicorn.log 2>&1 &