# .github/workflows/deploy.yml
name: CI/CD with Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/myaca-ai:latest

  deploy:
    name: Deploy to EC2
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          script: |
            # Pull the latest image from Docker Hub
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/myaca-ai:latest

            # Stop and remove the existing container if it is running
            docker stop myaca-ai-container || true
            docker rm myaca-ai-container || true

            # Create a .env file from the GitHub secret to pass to the container
            echo "${{ secrets.ENV_FILE }}" > .env

            # Run a new container with the updated image and environment variables
            # This maps port 80 on the EC2 instance to port 8000 inside the container
            docker run -d --name myaca-ai-container --env-file .env -p 8000:8000 ${{ secrets.DOCKERHUB_USERNAME }}/myaca-ai:latest
